slslambdaedge:
  component: "@sls-next/serverless-component@3.7.0-alpha.10"
  inputs:
    name:
      defaultLambda: DefaultLambda
      imageLambda: ImageLambda
    bucketRegion: us-east-1
    # bucketName: 'serverlesstest-dev-serverlessdeploymentbucket-1j4vl330f0qx'
    cloudfront:
      # distributionId: 'EI53H8SH173NY'
      comment: 'next deploy'